[/]
cursor-shape='block'
default-profile-uuid='fd37343a19226bcbb68fe24669d8c6d2'
font-name='Monospace 11'
interface-style='system'
profile-uuids=['fd37343a19226bcbb68fe24669d8c6d2']
text-blink-mode='focused'
use-system-font=false
window-size=(uint32 207, uint32 50)

[Profiles/fd37343a19226bcbb68fe24669d8c6d2]
cell-height-scale=1.0
cell-width-scale=1.0
palette='gnome-high-contrast'
