# main.yml
---

- name: Install rpmfusion
  dnf:
    state: present
    disable_gpg_check: yes
    name: "{{ rpmfusion_packages }}"
  become: yes
  when: ansible_os_family == "RedHat"
  tags: rpmfusion,become

- name: Enable powertools
  command: "dnf config-manager --set-enabled powertools"
  become: yes
  when: ansible_distribution == "CentOS"
  tags: rpmfusion,become

- name: Dnf tweaks
  blockinfile:
    path: /etc/dnf/dnf.conf
    create: yes
    block: |
      deltarpm=True
      fastestmirror=True
      install_weak_deps=False
      max_parallel_downloads=10
    mode: 0644
  become: yes
  when: ansible_os_family == "RedHat"
  tags: dnf,become

- name: Apt no recommends
  blockinfile:
    path: /etc/apt/apt.conf.d/01norecommend
    create: yes
    block: |
      APT::Install-Recommends "0";
      APT::Install-Suggests "0";
    mode: 0644
  become: yes
  when: ansible_os_family == "Debian"
  tags: apt,become

- name: Install CLI Packages
  include: terminal.yml
  tags: terminal
