# my_apps.yml
---

- name: Install Programs (Media Utilities)
  package:
    state: present
    name: "{{ codecs_packages }}"
  become: yes
  tags: codecs

- name: Install virtualization packages / Rpm
  dnf:
    name: "{{ virtualization_packages }}"
    state: present
    disable_gpg_check: yes
  become: yes
  when: ansible_os_family == "RedHat"
  tags: virtualization

- name: Install virtualization packages / Deb
  apt:
    name: "{{ virtualization_packages }}"
    state: present
  become: yes
  when: ansible_os_family == "Debian"
  tags: virtualization

- name: Install Main Programs
  package:
    state: present
    name: "{{ my_packages }}"
  become: yes
  tags: desktop_packages

- name: Install Programs (Flatpak Programs - flathub)
  command: "flatpak remote-add --user --if-not-exists {{ item.key }} {{ item.value }}"
  changed_when: no
  become: no
  with_items:
    - {key: "fedora", value: "oci+https://registry.fedoraproject.org"}
    - {key: "flathub", value: "https://flathub.org/repo/flathub.flatpakrepo"}
  when: use_flatpaks
  tags: flatpak_packages

- name: Install Programs (Flatpak Programs )
  command: "flatpak --user install -y flathub {{ item }}"
  with_items: "{{ flatpak_packages }}"
  register: flatpak_out
  changed_when: not 'already installed' in flatpak_out.stderr
  become: no
  when: use_flatpaks
  tags: flatpak_packages

- name: Remove duplicates (Flatpak Programs )
  command: "{{ pkg_mngr }} remove -y {{ ' '.join(flatpak_duplicate_packages) }}"
  register: pkg_out
  changed_when: pkg_out.stderr == 0
  become: yes
  when: use_flatpaks
  tags: flatpak_packages

- name: Env variables (Flatpak Programs)
  command: "flatpak override --user --env={{ item.value }} {{ item.key }}"
  with_items: "{{ flatpak_overrides }}"
  become: no
  when: use_flatpaks
  tags: flatpak_packages
