# my_apps.yml
---

- name: Install Programs (Codecs Packages)
  package:
    state: present
    name: "{{ codecs_packages }}"
  become: yes
  tags: codecs,become

- name: Install Programs (Programming Packages)
  package:
    state: present
    name: "{{ terminal_packages }}"
  become: yes
  tags: terminal,become

- name: Install Programs (python)
  package:
    state: present
    name: "{{ python_packages }}"
  become: yes
  tags: terminal,python,become

- name: Install Programs (PIP Packages) - pip
  shell: 'pip3 install --user {{ item }} | sed "s/Requirement already satisfied.*//g"'
  register: pip_output
  changed_when: pip_output.stdout_lines|length > 0
  with_items: "{{ python_modules }}"
  tags: terminal,python

- name: Install Programs (golang)
  package:
    state: present
    name: "{{ golang_packages }}"
  become: yes
  tags: terminal,golang,become

- name: Install Programs (Programming Packages) - golang
  package:
    name: "{{ golang_modules }}"
    state: present
  become: yes
  tags: terminal,golang,become
