---

- name: Git clone toolbox
  git:
    repo: 'https://github.com/89luca89/simpler-toolbox'
    dest: /tmp/simpler-toolbox
    force: yes
  tags: toolbox

- name: Deploy files
  copy:
    src: "/tmp/simpler-toolbox/{{ item }}"
    dest: "{{ ansible_env.HOME }}/.local/bin/{{ item }}"
    mode: '0755'
    remote_src: yes
  with_items:
    - toolbox_create
    - toolbox_enter
    - toolbox_export
    - toolbox_init
  tags: toolbox
