[default_distrobox]
image=debian:testing
pull=true
init=false
start_now=true
# Basic utilities for terminal use
additional_packages="apt-file dos2unix locales-all acpi lm-sensors linux-cpupower adb fastboot iotop iftop htop util-linux opus-tools mpv intel-media-va-driver mesa-va-drivers"
additional_packages="gawk moreutils parallel ncat bind9-utils net-tools openssl psmisc rsync rclone tree wl-clipboard curl wget socat"
# TUI Tools
additional_packages="jq tig tmux vim neomutt w3m ripgrep bubblewrap"
# Development packages
# missing gh
additional_packages="git git-email gitsign cosign kubernetes-client kind build-essential libsecret-1-0 libsecret-1-dev libglib2.0-dev gettext"
additional_packages="shellcheck bear clang clangd clang-tidy clang-tools codespell universal-ctags gcc shfmt golang rustup"
additional_packages="systemd-ukify sbsigntool ovmf erofs-utils btrfs-progs cryptsetup tpm2-tools swtpm"
# Python
additional_packages="python3 python3-pip pipx yamllint"
# Virtualization
additional_packages="qemu-system"
# Generic
init_hooks=ln -sf /usr/bin/distrobox-host-exec /usr/local/bin/docker
init_hooks=ln -sf /usr/bin/distrobox-host-exec /usr/local/bin/docker-compose
init_hooks=ln -sf /usr/bin/distrobox-host-exec /usr/local/bin/flatpak
init_hooks=ln -sf /usr/bin/distrobox-host-exec /usr/local/bin/podman
init_hooks=ln -sf /usr/bin/distrobox-host-exec /usr/local/bin/xdg-open
# check if we're online
init_hooks="ping -c1 1.1.1.1"
init_hooks=GOPATH="/usr/local/share/go" GOBIN=/usr/local/bin go install github.com/golangci/golangci-lint/v2/cmd/golangci-lint@latest
init_hooks=GOPATH="/usr/local/share/go" GOBIN=/usr/local/bin go install github.com/onsi/ginkgo/v2/ginkgo@latest
init_hooks=GOPATH="/usr/local/share/go" GOBIN=/usr/local/bin go install golang.org/x/tools/cmd/goimports@latest
init_hooks=GOPATH="/usr/local/share/go" GOBIN=/usr/local/bin go install golang.org/x/tools/gopls@latest
init_hooks=GOPATH="/usr/local/share/go" GOBIN=/usr/local/bin go install mvdan.cc/gofumpt@latest
init_hooks=pipx install --global jedi-language-server pylint mypy yapf yt-dlp
init_hooks=sudo -u \$container_user_name rustup default stable
init_hooks=sudo -u \$container_user_name rustup component add cargo clippy rust-docs rust-std rustc rustfmt rust-analyzer
init_hooks=make --directory=/usr/share/doc/git/contrib/credential/libsecret
init_hooks=echo done || echo distrobox: skipping not online
# Basic utilities for terminal use
exported_bins="/usr/bin/yt-dlp /usr/bin/mpv /usr/bin/wl-paste /usr/bin/wl-copy"
exported_bins="/usr/bin/shellcheck /usr/bin/ctags /usr/bin/bear"
exported_bins="/usr/share/doc/git/contrib/credential/libsecret/git-credential-libsecret"
