---

version: 2
# command define
commands:
  - title: Reload
    command: :reload-config

# linter,formatter setting
tools:

  sh-lint: &sh-lint
    lint-command: lint-project sh ${INPUT} lint
    lint-ignore-exit-code: true
    lint-stdin: false
    lint-formats:
      - '%f:%l: %m'
  man-hover: &man-hover
    hover-command: man ${INPUT}
    hover-stdin: false

  yaml-lint: &yaml-lint
    lint-command: lint-project yaml ${INPUT} lint
    lint-ignore-exit-code: true
    lint-stdin: false
    lint-formats:
      - '%f:%l: %m'

  ansible-lint: &ansible-lint
    lint-command: lint-project ansible.yaml ${INPUT} lint
    lint-ignore-exit-code: true
    lint-stdin: false
    lint-formats:
      - '%f:%l: %m'
  ansible-hover: &ansible-hover
    hover-command: ansible-doc ${INPUT}
    hover-stdin: false

  json-lint: &json-lint
    lint-command: lint-project json ${INPUT} lint
    lint-ignore-exit-code: true
    lint-stdin: false
    lint-formats:
      - '%f:%l: %m'

# languages setting
languages:

  sh:
    - <<: *sh-lint
    - <<: *man-hover

  yaml:
    - <<: *yaml-lint

  yaml.ansible:
    - <<: *ansible-lint
    - <<: *ansible-hover

  json:
    - <<: *json-lint

...
