version: 2
# command define
commands:
- title: Reload
  command: :reload-config

# linter,formatter setting
tools:

  sh-shellcheck: &sh-shellcheck
    lint-command: shellcheck -Cnever -a -f gcc -x
    lint-ignore-exit-code: true
    lint-formats:
    - '%f:%l:%c: %trror: %m'
    - '%f:%l:%c: %tarning: %m'
    - '%f:%l:%c: %tote: %m'

  shfmt-format: &shfmt-format
    format-command: shfm
    format-stdin: true

  man-hover: &man-hover
    hover-command: man ${INPUT}
    hover-stdin: false

  pylint-lint: &pylint-lint
    lint-command: pylint ${INPUT} -
    lint-ignore-exit-code: true
    lint-stdin: true
    lint-formats:
    - '%f:%l:%c: %m'

  yamllint-lint: &yamllint-lint
    lint-command: yamllint -d relaxed --format parsable ${INPUT}
    lint-ignore-exit-code: true
    lint-stdin: false
    lint-formats:
    - '%f:%l:%c: [%trror] %m'
    - '%f:%l:%c: [%tarning] %m'
    env:
    - PYTHONIOENCODING=UTF-8

  ansible-lint: &ansible-lint
    lint-command: ansible-lint -p --nocolor ${INPUT}
    lint-ignore-exit-code: true
    lint-stdin: false
    lint-formats:
    - '%f:%l: %m'
    env:
    - PYTHONIOENCODING=UTF-8

  golangci-lint: &golangci-lint
    lint-command: golangci ${INPUT}
    lint-ignore-exit-code: true
    lint-stdin: false
    lint-formats:
    - '%f:%l:%c %m'

# languages setting
languages:

  sh:
  - <<: *sh-shellcheck
  - <<: *shfmt-format
  - <<: *man-hover

  yaml:
  - <<: *yamllint-lint

  yaml.ansible:
  - <<: *yamllint-lint
    #  - <<: *ansible-lint

  python:
  - <<: *pylint-lint

  go:
  - <<: *golangci-lint
