---
version: 2
# command define
commands:
  - title: Reload
    command: :reload-config

  - title: Editor
    os: linux
    command: xdg-open
    # Linux no method generic GUI editor open
    arguments:
      - ${FILENAME}

  - title: Open
    os: linux
    command: xdg-open
    arguments:
      - ${FILENAME}

# linter,formatter setting
tools:

  sh-shellcheck: &sh-shellcheck
    lint-command: 'shellcheck -Cnever -a -f gcc -x'
    lint-formats:
      - '%f:%l:%c: %trror: %m'
      - '%f:%l:%c: %tarning: %m'
      - '%f:%l:%c: %tote: %m'

  shfmt-format: &shfmt-format
    format-command: 'shfmt -ln bash -kp'
    format-stdin: true

  pylint-lint: &pylint-lint
    lint-command: 'pylint ${INPUT} -'
    lint-stdin: true
    lint-formats:
      - '%f:%l:%c: %m'

  yamllint-lint: &yamllint-lint
    lint-command: 'yamllint --format parsable ${INPUT}'
    lint-stdin: false
    lint-formats:
      - '%f:%l: [%trror] %m'
      - '%f:%l: [%tarning] %m'
    env:
      - 'PYTHONIOENCODING=UTF-8'

  ansible-lint: &ansible-lint
    lint-command: 'ansible-lint -p --nocolor ${INPUT}'
    lint-stdin: false
    lint-formats:
      - '%f:%l: %m'
    env:
      - 'PYTHONIOENCODING=UTF-8'

        # golangci-lint: &golangci-lint
        #   lint-command: 'cd $(dirname ${INPUT}); golangci-lint run --fast --color never --enable-all --disable funlen,gomnd,gochecknoglobals .'
        #   lint-stdin: false
        #   lint-formats:
        #     - '%f:%l:%c: %m'

  goimports: &goimports
    format-command: 'goimports'
    format-stdin: true

  jsonlint: &jsonlint
    lint-command: 'jsonlint ${INPUT}'
    lint-stdin: false

  json-reformat: &json-reformat
    format-command: 'json_reformat'
    format-stdin: true

  xmllint: &xmllint
    lint-command: 'xmllint --noout ${INPUT}'
    lint-stdin: false

  xml-reformat: &xml-reformat
    format-command: 'xmllint --pretty 1 ${INPUT}'
    format-stdin: false

# languages setting
languages:

  sh:
    - <<: *sh-shellcheck
    - <<: *shfmt-format

  yaml:
    - <<: *yamllint-lint

  yaml.ansible:
    - <<: *yamllint-lint
    - <<: *ansible-lint

  python:
    - <<: *pylint-lint

  go:
    - <<: *goimports

  json:
    - <<: *jsonlint
    - <<: *json-reformat

  xml:
    - <<: *xmllint
    - <<: *xml-reformat
...
