---
# vars file for my_apps
#

use_flatpaks: yes

archive_packages:
  - cabextract
  - lzip
  - p7zip
  - p7zip-plugins
  - unzip
  - zstd

codecs_packages:
  - compat-ffmpeg28
  - compat-ffmpeg28-devel
  - egl-utils
  - egl-wayland
  - flac
  - ffmpeg
  - ffmpeg-libs
  - gstreamer1-libav
  - gstreamer1-plugins-bad-free
  - gstreamer1-plugins-bad-freeworld
  - gstreamer1-plugins-base
  - gstreamer1-plugins-base-tools
  - gstreamer1-plugins-good
  - gstreamer1-plugins-good-extras
  - gstreamer1-plugins-ugly
  - gstreamer1-plugins-ugly-free
  - gstreamer1-svt-av1
  - gstreamer1-svt-vp9
  - gstreamer1-vaapi
  - intel-media-driver
  - libva-devel
  - libva-intel-driver
  - libva-intel-hybrid-driver
  - libva-utils
  - libva-vdpau-driver
  - libvdpau-va-gl

virtualization_packages:
  - "@virtualization"

terminal_packages:
  - ShellCheck
  - acpi
  - android-tools
  - bash-completion
  - clang
  - clang-tools-extra
  - ctags
  - ctags-etags
  - dos2unix
  - flatpak
  - git
  - git-credential-libsecret
  - golang
  - lsof
  - make
  - net-tools
  - powertop
  - python3-devel
  - python3-pip
  - stow
  - tcpdump
  - tig
  - tlp
  - tree
  # Cli packages
  - aria2
  - mpv
  - ncdu
  - rsync
  - tmux
  - tmate
  - vim
  - syncthing
  - PackageKit
  # Generic X utility
  - setxkbmap
  - wmctrl
  - xbindkeys
  - xclip
  - xdotool
  - xgamma
  - xinput
  - xkill


### gnome-extensions-app gnome-tweaks
my_packages:
  - gnome-disk-utility
  - gnome-screenshot
  - gnome-system-monitor
  - gnome-terminal
  - gnome-terminal-nautilus
  - gvim
  - nautilus
  - nautilus-extensions
  #  - firefox
  #  - chromium-freeworld
  #  - baobab
  #  - cheese
  #  - drawing
  #  - eog
  #  - evince
  #  - file-roller
  #  - gcolor3
  #  - gedit
  #  - gigolo
  #  - krita
  #  - gnome-sound-recorder
  #  - gnome-calculator
  #  - gnome-calendar
  #  - gnome-connections
  #  - gnome-contacts
  #  - gnome-firmware
  #  - gnome-logs
  #  - gnome-maps
  #  - gnome-network-displays
  #  - gnome-weather
  #  - keepassxc
  #  - pdfarranger
  #  - remmina
  #  - rhythmbox
  #  - thunderbird
  #  - totem
  #  - pidgin

debloat_pkg:
  - abrt
  - abrt-addon-ccpp
  - abrt-addon-kerneloops
  - abrt-addon-pstoreoops
  - abrt-addon-vmcore
  - abrt-addon-xorg
  - abrt-cli
  - abrt-dbus
  - abrt-desktop
  - abrt-gui
  - abrt-gui-libs
  - abrt-java-connector
  - abrt-libs
  - abrt-plugin-bodhi
  - abrt-retrace-client
  - abrt-tui
  - anaconda-install-env-deps
  - fedora-logos-httpd
  - gamemode
  - gnome-boxes
  - gnome-dictionary
  - gnome-documents
  - gnome-music
  - gnome-online-miners
  - gnome-photos
  - gnome-shell-extension-background-logo
  - gnome-user-docs
  - gnome-user-share
  - httpd
  - hyperv-daemons
  - hyperv-daemons-license
  - hypervfcopyd
  - hypervkvpd
  - hypervvssd
  - open-vm-tools-desktop
  - orca
  - qemu-guest-agent
  - rsyslog
  - spice-vdagent
  - virtualbox-guest-additions
  - yelp
  - yelp-libs
  - yelp-xsl
