---
# vars file for my_apps
#

terraform_provider_libvirt_url: "https://github.com/dmacvicar/terraform-provider-libvirt/releases/download/v{{ terraform_provider_libvirt_version }}/terraform-provider-libvirt-{{ terraform_provider_libvirt_release }}.Fedora_32.x86_64.tar.gz"

terminal_packages:
  - ShellCheck
  - acpi
  - android-tools
  - bash-completion
  - clang
  - clang-tools-extra
  - ctags
  - ctags-etags
  - flatpak
  - git
  - git-credential-libsecret
  - golang
  - libappindicator
  - libappindicator-gtk3
  - lsof
  - make
  - net-tools
  - powertop
  - python3-devel
  - python3-pip
  - ripgrep
  - stunnel
  - tcpdump
  - tlp
  - zbar

my_packages:
  - chromium-freeworld
  - evince
  - file-roller
  - firefox
  - gimp
  - gnome-disk-utility
  - gnome-screenshot
  - gnome-terminal
  - gnome-keyring
  - gnome-keyring-pam
  - gvim
  - libreoffice-calc
  - libreoffice-draw
  - libreoffice-gtk3
  - libreoffice-impress
  - libreoffice-writer
  - pinta
  # Cli packages
  # - arandr
  # - nitrogen
  - aria2
  - mpv
  - ncdu
  - pass
  - pass-otp
  - ranger
  - rofi
  - rsync
  - syncthing
  - tmux
  - vim
  - w3m
  - papirus-icon-theme
  - pinentry-gtk
  # Generic X utility
  - devilspie2
  - setxkbmap
  - wmctrl
  - xbindkeys
  - xclip
  - xdotool
  - xgamma
  - xinput

debloat_pkg:
  - PackageKit
  - PackageKit-glib
  - abrt
  - abrt-addon-ccpp
  - abrt-addon-kerneloops
  - abrt-addon-pstoreoops
  - abrt-addon-vmcore
  - abrt-addon-xorg
  - abrt-cli
  - abrt-dbus
  - abrt-desktop
  - abrt-gui
  - abrt-gui-libs
  - abrt-java-connector
  - abrt-libs
  - abrt-plugin-bodhi
  - abrt-retrace-client
  - abrt-tui
  - gnome-boxes
  - gnome-calendar
  - gnome-contacts
  - gnome-dictionary
  - gnome-documents
  - gnome-getting-started-docs
  - gnome-initial-setup
  - gnome-maps
  - gnome-music
  - gnome-online-miners
  - gnome-photos
  - gnome-software
  - gnome-user-docs
  - gnome-user-share
  - gnome-video-effects
  - gnome-weather
  - httpd
  - open-vm-tools-desktop
  - rsyslog
  - xarchiver
  - xfce4-screenshooter
  - xfdashboard
  - xfdesktop
  - yelp
  - yelp-libs
  - yelp-xsl
  - akregator
  - dragonplayer
  - juk
  - kaddressbook
  - kcolorchooser
  - kget
  - kgpg
  - kmag
  - kmahjongg
  - kmail
  - kmines
  - kmousetool
  - kmouth
  - kolourpaint
  - kontact
  - konversation
  - korganizer
  - kpat
  - krdc
  - krfb
  - kruler
  - ktnef
  - kwrite
  - mediawriter
