---
# tasks file for debloat

- name: Remove Programs (Unused Programs)
  package:
    name: "{{ debloat_pkg }}"
    state: absent
  become: true
  tags: debloat

# Mask systemd services to free up memory
- name: Mask services /1
  systemd:
    name: "{{ item }}"
    state: stopped
    enabled: false
    masked: true
    daemon_reload: true
    scope: user
  with_items: "{{ systemd_user_mask_services }}"
  become: false
  tags: debloat

# Mask systemd services to free up memory
- name: Mask services /2
  systemd:
    name: "{{ item }}"
    state: stopped
    enabled: false
    masked: true
    daemon_reload: true
  with_items: "{{ systemd_root_mask_services }}"
  become: true
  tags: debloat

- name: Find tracker files
  find:
    paths: /usr/libexec/
    file_type: file
    recurse: Yes
    patterns: "tracker-*"
  register: files_matched
  tags: debloat

- name: Debug files_matched loop
  shell: |
    mv {{ item.path }} "$(dirname {{ item.path }})"/disabled_"$(basename {{ item.path }})"
  loop: "{{ files_matched.files|flatten(levels=1) }}"
  become: true
  tags: debloat

# EXTREME Debloat, remove also virtualization containers support
# RUN EXPLICITELY
- name: Remove Programs (Extreme)
  package:
    name: "{{ debloat_pkg_extreme }}"
    state: absent
  become: true
  tags: never, extreme_debloat

- name: Deploy Grub Flags
  replace:
    path: /etc/default/grub
    regexp: 'mmc_mod.use_blk_mq=1"$'
    replace: 'mmc_mod.use_blk_mq=1 mitigations=off dis_ucode_ldr"'
    backup: true
  register: grub_setup
  become: true

- name: Update Grub and Initramfs
  command: '{{ item }}'
  with_items:
    - 'grub2-mkconfig -o /boot/grub2/grub.cfg'
    - 'dracut --force --regenerate-all -v'
  when: grub_setup.changed
  become: true
