# ctrl-a
set -g prefix C-a
bind C-a send-prefix
bind-key a send-prefix
unbind C-b
# qol
set -g base-index 1
set -g mouse on
set -g pane-base-index 1
set -g renumber-windows on
set -s copy-command 'wl-copy'
set -g default-terminal "xterm-256color"
# keybind
bind o setw synchronize-panes
bind s split-window -v -c "#{pane_current_path}"
bind v split-window -h -c "#{pane_current_path}"
# status bar
sync_ind_colour="#{?pane_synchronized,yellow,colour145}"
set -g pane-border-style fg=colour240
set -g status-interval 5
set -g status-style "bg=default"
set -g window-status-current-format "#[bg=${sync_ind_colour},fg=black,bold]  #I:#W \+  "
set -g status-left ""
set -g status-right "#[fg=default,bold]#(~/.local/bin/tmux-status) "
set -g status-right-length 160
