---
# tasks file to setup become,distro to my liking

- name: Install Power Management (Laptop)
  package:
    state: present
    name: "{{ power_management_packages }}"
  tags: become,distro,powersave

- name: Disable WIFI Mac address randomization on scan
  blockinfile:
    path: /etc/NetworkManager/conf.d/30-mac-randomization.conf
    create: yes
    block: |
      [device-mac-randomization]
      wifi.scan-rand-mac-address=no
    mode: 0644
  tags: become,distro

- name: Set sysctl variables
  sysctl:
    name: '{{ item.name }}'
    value: '{{ item.value }}'
    sysctl_set: yes
    state: present
    reload: yes
  with_items:
    - {name: vm.laptop_mode, value: 5}
    - {name: kernel.nmi_watchdog, value: 0}
    - {name: vm.swappiness, value: 5}
    - {name: vm.oom_kill_allocating_task, value: 1}
    - {name: vm.vfs_cache_pressure, value: 1000}
    - {name: vm.dirty_ratio, value: 90}
    - {name: vm.dirty_background_ratio, value: 50}
    - {name: vm.dirty_writeback_centisecs, value: 1500}
    - {name: vm.dirty_expire_centisecs, value: 60000}
    - {name: fs.inotify.max_user_watches, value: 524288}
    - {name: net.ipv4.ip_default_ttl, value: 66}
  tags: become,distro

- name: Set zram size
  blockinfile:
    path: /etc/systemd/zram-generator.conf
    create: yes
    block: |
      [zram0]
      zram-fraction=0.5
      max-zram-size=16384
    marker: "# {mark} ANSIBLE MANAGED BLOCK BY DOTFILES"
    mode: 0600
  tags: become,distro,zram

- name: Set UDev Rules
  blockinfile:
    path: /etc/udev/rules.d/powersave.rules
    create: yes
    block: |
      ACTION=="add|change", SUBSYSTEM=="acpi", ATTR{power/control}="auto"
      ACTION=="add|change", SUBSYSTEM=="ahci", ATTR{power/control}="auto"
      ACTION=="add|change", SUBSYSTEM=="block", ATTR{power/control}="auto"
      ACTION=="add|change", SUBSYSTEM=="i2c", ATTR{power/control}="auto"
      ACTION=="add|change", SUBSYSTEM=="net", KERNEL=="enp*", RUN+="/usr/sbin/ethtool -s %k wol d"
      ACTION=="add|change", SUBSYSTEM=="net", KERNEL=="wlp*", RUN+="/usr/sbin/iw dev %k set power_save on"
      ACTION=="add|change", SUBSYSTEM=="pci", ATTR{power/control}="auto"
      ACTION=="add|change", SUBSYSTEM=="scsi", ATTR{power/control}="auto"
      ACTION=="add|change", SUBSYSTEM=="scsi_host", KERNEL=="host*", ATTR{link_power_management_policy}="min_power"
      ACTION=="add|change", SUBSYSTEM=="usb", ATTR{power/autosuspend}="1"
      ACTION=="add|change", SUBSYSTEM=="workqueue", ATTR{power/control}="auto"
      ACTION=="add|change", KERNEL=="sd[a-z]", ATTR{queue/iosched/low_latency}="1"
      ACTION=="add|change", KERNEL=="sd[a-z]", ATTR{queue/scheduler}="bfq"
      ACTION=="add|change", KERNEL=="sd[a-z]", ATTR{queue/read_ahead_kb}="4096"
      ACTION=="add|change", KERNEL=="nvme[0-9]n[0-9]", ATTR{queue/read_ahead_kb}="16384"
      # ACTION=="add|change", SUBSYSTEM=="power_supply", RUN+="/usr/sbin/powertop --auto-tune"
      # SUBSYSTEM=="power_supply",ENV{POWER_SUPPLY_ONLINE}=="0",RUN+="/usr/sbin/powertop --auto-tune"
    marker: "# {mark} ANSIBLE MANAGED BLOCK BY DOTFILES"
    mode: 0600
  tags: become,distro,powersave

- name: Set Powersave script
  copy:
    dest: /usr/local/bin/powersaver
    content: |
      #!/bin/sh
      # List PCI devices with ASPM disabled, and set them
      # enabled using setpu
      for pci in $(/sbin/lspci | cut -d" " -f1); do
          if /sbin/lspci -vv -s "$pci" | grep -q "ASPM Disabled"; then
              /sbin/setpci -s "$pci" 0x80.B=0x43
          fi
      done
      if grep -q Discharging /sys/class/power_supply/BAT*/status ; then
      # Battery mode.
          /usr/local/bin/ryzenadj --power-saving
          echo "low-power" > /sys/firmware/acpi/platform_profile
          logger "Enabling powersave"
      else
      # AC Mode.
          /usr/local/bin/ryzenadj --max-performance
          echo "performance" > /sys/firmware/acpi/platform_profile
          logger "Enabling performance"
      fi
      if [ "$(cat /sys/block/nvme0n1/queue/read_ahead_kb)" != 16384 ]; then
              /bin/udevadm trigger
      fi
    mode: 0755
  tags: become,distro,powersave

- name: Set Powersave unit /service
  blockinfile:
    path: /etc/systemd/system/powersaver.service
    create: yes
    block: |
      [Unit]
      Description=powersaver

      [Service]
      Type=oneshot
      ExecStart=/usr/local/bin/powersaver
      WorkingDirectory=/usr/local/bin
    mode: 0644
  tags: become,distro,powersave

- name: Set Powersave unit /timer
  blockinfile:
    path: /etc/systemd/system/powersaver.timer
    create: yes
    block: |
      [Unit]
      Description=powersaver

      [Timer]
      OnActiveSec=0
      OnUnitActiveSec=60
      AccuracySec=500msec

      [Install]
      WantedBy=timers.target
    mode: 0644
  tags: become,distro,powersave

- name: Enable Powersave unit
  systemd:
    name: powersaver.timer
    state: started
    enabled: yes
  tags: become,distro,powersave

- name: Set driver powersave options
  blockinfile:
    path: /etc/modprobe.d/powersave.conf
    create: yes
    block: |
      options amdgpu dc=1 si_support=1 cik_support=1 dcfeaturemask=0xB aspm=1
      options dm_mod use_blk_mq=1
      options drm debug=0 vblankoffdelay=1
      options e1000e SmartPowerDownEnable=1
      options i915 disable_power_well=0 enable_dc=2 enable_psr=1 enable_rc6=7 enable_fbc=1 powersave=1 enable_guc=3
      options iwlwifi power_save=Y power_level=5
      options iwlmvm power_scheme=3
      options mmc_mod use_blk_mq=1
      options nvme_core default_ps_max_latency_us=20000 force_apst=1
      options scsi_mod use_blk_mq=1
      options snd_ac97_codec power_save=1
      options snd_hda_intel power_save_controller=Y power_save=1
      options thinkpad_acpi fan_control=1
      options usbcore autosuspend=1
    mode: 0644
  tags: become,distro,powersave

- name: Check if lvm.conf is present
  stat:
    path: /etc/lvm/lvm.conf
  register: lvm_file
  tags: become,distro

- name: Deploy lvm.conf Flags
  replace:
    path: /etc/lvm/lvm.conf
    regexp: 'issue_discards = 0'
    replace: 'issue_discards = 1'
    backup: yes
  register: lvm_setup
  when: lvm_file.stat.exists
  tags: become,distro

- name: Check if Crypttab is present
  stat:
    path: /etc/crypttab
  register: crypt_file
  tags: become,distro

- name: Deploy Crypttab Performance Flags
  replace:
    path: /etc/crypttab
    regexp: 'none discard$'
    replace: 'none discard,no-read-workqueue,no-write-workqueue'
    backup: yes
  register: crypt_setup
  when: crypt_file.stat.exists
  tags: become,distro

- name: Deploy Grub Flags
  replace:
    path: /etc/default/grub
    regexp: '^(GRUB_CMDLINE_LINUX=(?:(?![" ]{{ item.option | regex_escape }}=).)*)(?:[" ]{{ item.option | regex_escape }}=\S+)?(.*")$'
    replace: '\1 {{ item.option }}={{ item.value }}\2'
    backup: yes
  with_items:
    # Powersaving drivers
    - {option: amdgpu.aspm, value: 1}
    - {option: amdgpu.cik_support, value: 1}
    - {option: amdgpu.dc, value: 1}
    - {option: amdgpu.dcfeaturemask, value: '0xB'}
    - {option: amdgpu.si_support, value: 1}
    - {option: dm_mod.use_blk_mq, value: 1}
    - {option: drm.debug, value: 0}
    - {option: drm.vblankoffdelay, value: 1}
    - {option: i915.disable_power_well, value: 0}
    - {option: i915.enable_dc, value: 2}
    - {option: i915.enable_fbc, value: 1}
    - {option: i915.enable_guc, value: 3}
    - {option: i915.enable_psr, value: 1}
    - {option: i915.enable_rc6, value: 7}
    - {option: i915.powersave, value: 1}
    - {option: mmc_mod.use_blk_mq, value: 1}
    - {option: nvme_core.default_ps_max_latency_us, value: 20000}
    - {option: nvme_core.force_apst, value: 1}
    - {option: pcie_aspm, value: force}
    - {option: pcie_aspm.policy, value: powersupersave}
    - {option: scsi_mod.use_blk_mq, value: 1}
    - {option: usbcore.autosuspend, value: 1}
  register: grub_conf
  tags: become,distro,grub

- name: Set Grub Rules
  blockinfile:
    path: /etc/default/grub
    create: yes
    block: |
        GRUB_DISABLE_OS_PROBER=true
        GRUB_DISABLE_RECOVERY=true
        GRUB_DISABLE_SUBMENU=true
        GRUB_GFXMODE=640x480
        GRUB_RECORDFAIL_TIMEOUT=0
        GRUB_TIMEOUT=0
        GRUB_TIMEOUT_QUIET=true
        GRUB_HIDDEN_TIMEOUT_QUIET=true
        GRUB_TIMEOUT_STYLE=hidden
    marker: "# {mark} ANSIBLE MANAGED BLOCK"
    mode: 0600
  register: grub_setup
  tags: distro,grub

- name: Update Grub and Initramfs /RedHat
  shell: "{{ item }}"
  with_items:
    - "for grub in $(find /boot -name grub.cfg); do grub2-mkconfig -o $grub; done"
    - "dracut --force --regenerate-all"
  when: >
    ((grub_conf is defined and grub_conf.changed) or
    (grub_setup is defined and grub_setup.changed) or
    (lvm_setup is defined and lvm_setup.changed) or
    (crypt_setup is defined and crypt_setup.changed))
    and ansible_os_family == "RedHat"
  tags: become,distro,grub

- name: Update Grub and Initramfs /Debian
  command: "{{ item }}"
  with_items:
    - "update-grub"
    - "update-initramfs -k all -u"
  when: >
    ((grub_conf is defined and grub_conf.changed) or
    (grub_setup is defined and grub_setup.changed) or
    (lvm_setup is defined and lvm_setup.changed) or
    (crypt_setup is defined and crypt_setup.changed))
    and ansible_os_family == "Debian"
  tags: become,distro,grub
