---
# tasks file to setup distro to my liking

- name: Set sysctl variables
  sysctl:
    name: '{{ item.name }}'
    value: '{{ item.value }}'
    sysctl_set: yes
    state: present
    reload: yes
  with_items:
    - {name: vm.laptop_mode, value: 5}
    - {name: kernel.nmi_watchdog, value: 0}
    - {name: vm.swappiness, value: 5}
    - {name: vm.oom_kill_allocating_task, value: 1}
  tags: distro,sysctl

- name: Fix audio
  blockinfile:
    path: /etc/pipewire/pipewire.conf.d/fix.conf
    create: yes
    block: |
      context.properties = {
        default.clock.allowed-rates  = [ 48000 ]
        default.clock.quantum = 4096
        default.clock.min-quantum = 2048
        default.clock.max-quantum = 8192
      }
    marker: "# {mark} ANSIBLE MANAGED BLOCK BY DOTFILES"
    mode: 0644
  tags: distro,audio

- name: Fix network privacy - mac randomization
  blockinfile:
    path: /etc/NetworkManager/conf.d/00-macrandomize.conf
    create: yes
    block: |
      [device]
      wifi.scan-rand-mac-address=yes

      [connection]
      wifi.cloned-mac-address=random
      ethernet.cloned-mac-address=random
    marker: "# {mark} ANSIBLE MANAGED BLOCK BY DOTFILES"
    mode: 0644
  tags: distro,network

- name: Fix network privacy - hostname
  blockinfile:
    path: /etc/NetworkManager/conf.d/01-transient-hostname.conf
    create: yes
    block: |
      [main]
      hostname-mode=none
    marker: "# {mark} ANSIBLE MANAGED BLOCK BY DOTFILES"
    mode: 0644
  tags: distro,network

- name: Set UDev Rules
  blockinfile:
    path: /etc/udev/rules.d/powersave.rules
    create: yes
    block: |
      ACTION=="add|change", SUBSYSTEM=="acpi", ATTR{power/control}="auto"
      ACTION=="add|change", SUBSYSTEM=="ahci", ATTR{power/control}="auto"
      ACTION=="add|change", SUBSYSTEM=="block", ATTR{power/control}="auto"
      ACTION=="add|change", SUBSYSTEM=="i2c", ATTR{power/control}="auto"
      ACTION=="add|change", SUBSYSTEM=="net", KERNEL=="enp*", RUN+="/usr/sbin/ethtool -s %k wol d"
      ACTION=="add|change", SUBSYSTEM=="net", KERNEL=="wlp*", RUN+="/usr/sbin/iw dev %k set power_save on"
      ACTION=="add|change", SUBSYSTEM=="pci", ATTR{power/control}="auto"
      ACTION=="add|change", SUBSYSTEM=="scsi", ATTR{power/control}="auto"
      ACTION=="add|change", SUBSYSTEM=="scsi_host", KERNEL=="host*", ATTR{link_power_management_policy}="min_power"
      ACTION=="add|change", SUBSYSTEM=="usb", ATTR{power/autosuspend}="1"
      ACTION=="add|change", SUBSYSTEM=="workqueue", ATTR{power/control}="auto"
      ACTION=="add|change", KERNEL=="sd[a-z]", ATTR{queue/iosched/low_latency}="1"
      ACTION=="add|change", KERNEL=="sd[a-z]", ATTR{queue/scheduler}="bfq"
      ACTION=="add|change", KERNEL=="sd[a-z]", ATTR{queue/read_ahead_kb}="4096"
      ACTION=="add|change", KERNEL=="nvme[0-9]n[0-9]", ATTR{queue/read_ahead_kb}="16384"
      # ACTION=="add|change", SUBSYSTEM=="power_supply", RUN+="/usr/sbin/powertop --auto-tune"
      # SUBSYSTEM=="power_supply",ENV{POWER_SUPPLY_ONLINE}=="0",RUN+="/usr/sbin/powertop --auto-tune"
    marker: "# {mark} ANSIBLE MANAGED BLOCK BY DOTFILES"
    mode: 0600
  tags: distro,powersave

- name: Check if lvm.conf is present
  stat:
    path: /etc/lvm/lvm.conf
  register: lvm_file
  tags: distro,lvm

- name: Deploy lvm.conf Flags
  replace:
    path: /etc/lvm/lvm.conf
    regexp: 'issue_discards = 0'
    replace: 'issue_discards = 1'
    backup: yes
  register: lvm_setup
  when: lvm_file.stat.exists
  tags: distro,lvm

- name: Check if Crypttab is present
  stat:
    path: /etc/crypttab
  register: crypt_file
  tags: distro,crypttab

- name: Deploy Crypttab Performance Flags
  replace:
    path: /etc/crypttab
    regexp: 'none discard$'
    replace: 'none discard,no-read-workqueue,no-write-workqueue'
    backup: yes
  register: crypt_setup
  when: crypt_file.stat.exists
  tags: distro,crypttab

- name: Deploy Crypttab Performance Flags /2
  replace:
    path: /etc/crypttab
    regexp: 'x-initrd.attach$'
    replace: 'x-initrd.attach,discard,no-read-workqueue,no-write-workqueue'
    backup: yes
  register: crypt_setup
  when: crypt_file.stat.exists
  tags: distro,crypttab

- name: Deploy Grub Flags
  replace:
    path: /etc/default/grub
    regexp: '^(GRUB_CMDLINE_LINUX=(?:(?![" ]{{ item.option | regex_escape }}=).)*)(?:[" ]{{ item.option | regex_escape }}=\S+)?(.*")$'
    replace: '\1 {{ item.option }}={{ item.value }}\2'
    backup: yes
  with_items:
    # Powersaving drivers
    - {option: amdgpu.aspm, value: 1}
    - {option: amdgpu.cik_support, value: 1}
    - {option: amdgpu.dc, value: 1}
    - {option: amdgpu.dcfeaturemask, value: '0xB'}
    - {option: amdgpu.si_support, value: 1}
    - {option: dm_mod.use_blk_mq, value: 1}
    - {option: drm.debug, value: 0}
    - {option: drm.vblankoffdelay, value: 1}
    - {option: e1000e.SmartPowerDownEnable, value: 1}
    - {option: i915.disable_power_well, value: 0}
    - {option: i915.enable_dc, value: 2}
    - {option: i915.enable_fbc, value: 1}
    - {option: i915.enable_guc, value: 3}
    - {option: i915.enable_psr, value: 1}
    - {option: i915.enable_rc6, value: 7}
    - {option: i915.powersave, value: 1}
    - {option: iwlmvm.power_scheme, value: 3}
    - {option: iwlwifi.power_level, value: 5}
    - {option: iwlwifi.power_save, value: "Y"}
    - {option: mmc_mod.use_blk_mq, value: 1}
    - {option: nvme_core.default_ps_max_latency_us, value: 20000}
    - {option: nvme_core.force_apst, value: 1}
    - {option: pcie_aspm, value: force}
    - {option: pcie_aspm.policy, value: powersupersave}
    - {option: scsi_mod.use_blk_mq, value: 1}
    - {option: thinkpad_acpi.fan_control, value: 1}
    - {option: usbcore.autosuspend, value: 1}
  register: grub_conf
  tags: distro,grub
# - {option: snd_ac97_codec.power_save, value: 1}
# - {option: snd_hda_intel.power_save, value: 1}
# - {option: snd_hda_intel.power_save_controller, value: "Y"}
# - {option: mitigations, value: "off"}

- name: Validate Grub Config
  command: grub2-mkconfig
  changed_when: no
  tags: distro,grub
