---

- name: Create a directory if it does not exist
  file:
    path: "{{ ansible_env.HOME }}/.local/share/fonts"
    state: directory
    mode: '0700'
  tags: distro,fonts

- name: Ensure truetype directory exists
  stat:
    path: "{{ ansible_env.HOME }}/.local/share/fonts/truetype"
  register: truetype_folder
  tags: distro,fonts

- name: Install MS Fonts
  get_url:
    url: "{{ fonts_url }}"
    dest: "{{ ansible_env.HOME }}/Downloads/mss-truetype-fonts.tar.gz"
    username: "{{ basicauth_user }}"
    password: "{{ basicauth_pass }}"
    checksum: sha256:69e6164432000c93e81d8298f840c528acc9e280732647d5b82ac6d525179558
  when: not truetype_folder.stat.exists
  tags: distro,fonts

- name: Extract fonts
  unarchive:
    src: "{{ ansible_env.HOME }}/Downloads/mss-truetype-fonts.tar.gz"
    dest: "{{ ansible_env.HOME }}/.local/share/fonts/"
    creates: "{{ ansible_env.HOME }}/.local/share/fonts/truetype"
  tags: distro,fonts
