# main.yml
---

# Mask systemd services to free up memory
- name: Mask services /1
  systemd:
    name: "{{ item }}"
    state: stopped
    enabled: no
    masked: yes
    daemon_reload: yes
    scope: user
  with_items: "{{ systemd_user_mask_services }}"
  become: no
  retries: 3
  delay: 3
  register: result
  until: result is not failed
  tags: distro


# Mask systemd services to free up memory
- name: Mask services /2
  systemd:
    name: "{{ item }}"
    state: stopped
    enabled: no
    masked: yes
    daemon_reload: yes
  with_items: "{{ systemd_root_mask_services }}"
  become: yes
  retries: 3
  delay: 3
  register: result
  until: result is not failed
  tags: distro,become

- name: Include distro setup
  include: distro.yml
  tags: distro,become

- name: Install Podman Packages
  include: podman.yml
  become: yes
  tags: podman,become

- name: Install Main Packages
  include: packages.yml
  tags: packages,become

- name: Install Flatpak Packages
  include: flatpak.yml
  tags: flatpak
