# main.yml
---

- name: Include systemd setup
  include: systemd.yml
  tags: systemd

- name: Include distro setup
  include: distro.yml
  tags: distro

- name: Include flatpak setup
  include: distro.yml
  tags: flatpak
