# main.yml
---

- name: Include systemd setup
  import_tasks: systemd.yml
  become: yes
  tags: systemd

- name: Include distro setup
  import_tasks: distro.yml
  become: yes
  tags: distro

- name: Include flatpak setup
  import_tasks: flatpak.yml
  become: no
  tags: flatpak
