# my_apps.yml
---

- name: Install virtualization packages / Rpm
  dnf:
    name: "{{ virtualization_packages }}"
    state: present
    disable_gpg_check: yes
  become: yes
  when: ansible_os_family == "RedHat"
  tags: virtualization,become

- name: Install virtualization packages / Deb
  apt:
    name: "{{ virtualization_packages }}"
    state: present
  become: yes
  when: ansible_os_family == "Debian"
  tags: virtualization,become

- name: Install virtualization packages / Suse
  shell: "pkcon -y --allow-reinstall install {{ virtualization_packages | join(' ') }}"
  become: yes
  when: ansible_os_family | lower | regex_search('suse')
  tags: virtualization,become

- name: Install Main Programs
  shell: "pkcon -y --allow-reinstall install {{ my_packages | join(' ') }}"
  become: yes
  tags: desktop_packages,become
