# my_apps.yml
---

- name: Install virtualization packages / Rpm
  dnf:
    name: "{{ virtualization_packages }}"
    state: present
    disable_gpg_check: yes
  become: yes
  when: ansible_os_family == "RedHat"
  tags: virtualization,become

- name: Install virtualization packages / Deb
  apt:
    name: "{{ virtualization_packages }}"
    state: present
  become: yes
  when: ansible_os_family == "Debian"
  tags: virtualization,become

- name: Install virtualization packages / Suse
  shell: "pkcon refresh; pkcon -y install {{ virtualization_packages | join(' ') }}"
  become: yes
  retries: 3
  delay: 30
  register: result
  until: result is not failed
  changed_when: not result.stdout | regex_search('already installed')
  failed_when: result.rc != 0 and (not result.stdout | regex_search('already installed'))
  when: ansible_os_family | lower | regex_search('suse')
  tags: virtualization,become

- name: Install Main Programs
  shell: "pkcon refresh; pkcon -y install {{ my_packages | join(' ') }}"
  become: yes
  retries: 3
  delay: 30
  register: result
  until: result is not failed
  changed_when: not result.stdout | regex_search('already installed')
  failed_when: result.rc != 0 and (not result.stdout | regex_search('already installed'))
  tags: desktop_packages,become
