---

- name: Setup podman repo (Debian Family)
  block:
    - name: Check if repo is present
      stat:
        path: /etc/apt/sources.list.d/devel:kubic:libcontainers:stable.list
      register: podman_repo

    - name: Configure podman repos
      shell: |
          . /etc/os-release
          echo "deb https://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable/xUbuntu_${VERSION_ID}/ /" | tee /etc/apt/sources.list.d/devel:kubic:libcontainers:stable.list
          curl -L "https://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable/xUbuntu_${VERSION_ID}/Release.key" | apt-key add -
      when: not podman_repo.stat.exists

    - name: Apt update
      command: apt update
      changed_when: no

    - name: Install podman
      package:
        name: "{{ item }}"
        state: present
      with_items:
        - podman

  when: ansible_os_family == "Debian"
  tags: podman,become
