# my_apps.yml

---

- name: Install Programs (GUI Programs)
  package:
    state: latest
    name: "{{ my_packages }}"
  become: true

- name: Install onlyoffice
  dnf:
    state: present
    name: "{{ item }}"
  with_items:
    - https://download.onlyoffice.com/repo/centos/main/noarch/onlyoffice-repo.noarch.rpm
  become: true
  tags: onlyoffice

- name: Install onlyoffice
  dnf:
    state: present
    name: "{{ item }}"
  with_items:
    - onlyoffice-desktopeditors
  become: true
  tags: onlyoffice

- name: Ensure Folders Exists
  file:
    path: '{{ item }}'
    state: directory
  with_items:
    - "{{ ansible_env.HOME }}/Programs"
    - "{{ ansible_env.HOME }}/.local/share/icons"
    - "{{ ansible_env.HOME }}/.local/share/applications"
  tags: appimage

- name: Download appimages
  get_url:
    url: "{{ item.url }}"
    dest: "{{ item.dest }}"
    mode: 0755
  with_items: "{{ appimages_packages }}"
  tags: appimage

- name: Download appimages
  blockinfile:
    path: '{{ ansible_env.HOME }}/.local/share/applications/{{ item.name }}.desktop'
    create: true
    block: |
      [Desktop Entry]
      Name={{ item.label }}
      Exec={{ item.dest }} %F
      Terminal=false
      Type=Application
      Icon={{ item.name }}
      Categories=Office;TextEditor;Utility;
      MimeType=text/markdown;
      Keywords={{ item.name }};
      StartupWMClass={{ item.name }}
      Actions=NewWindow;
      [Desktop Action NewWindow]
      Name=New Window
      Exec={{ item.dest }} --new-window %F
      Icon={{ item.name }}
  with_items: "{{ appimages_entries }}"
  tags: appimage

- name: Setup VSCodium repo
  blockinfile:
    path: /etc/yum.repos.d/vscodium.repo
    create: true
    block: |
      [gitlab.com_paulcarroty_vscodium_repo]
      name=gitlab.com_paulcarroty_vscodium_repo
      baseurl=https://gitlab.com/paulcarroty/vscodium-deb-rpm-repo/raw/repos/rpms/
      enabled=1
      gpgcheck=1
      repo_gpgcheck=1
      gpgkey=https://gitlab.com/paulcarroty/vscodium-deb-rpm-repo/raw/master/pub.gpg
  become: true
  tags: vscodium

- name: Installing latest VSCodium
  dnf:
    name: codium
    state: latest
  become: true
  tags: vscodium

- name: Ensure VSCodium folders exist
  file:
    path: "{{ ansible_env.HOME }}/.config/VSCodium/User/"
    state: directory
  tags: vscodium

- name: Configuring VSCodium
  template:
    src: settings.json.j2
    dest: "{{ ansible_env.HOME }}/.config/VSCodium/User/settings.json"
  tags: vscodium

- name: Libinput Gestures (Clone)
  git:
    repo: https://github.com/bulletmark/libinput-gestures
    dest: '{{ ansible_env.HOME }}/Programs/libinput-gestures'
    version: master
    update: true
  register: libinput_gesture_download
  tags: libinput_gestures

- name: Libinput Gestures (Add "{{ lookup('env','USER') }}" to Input Group)
  user:
    name: "{{ lookup('env','USER') }}"
    groups: input
    append: yes
  become: true
  tags: libinput_gestures

- name: Libinput Gestures (Dependencies)
  package:
    state: latest
    name:
      - systemd-devel
      - libinput-devel
  become: true
  tags: libinput_gestures

- name: Libinput Gestures (Compile and Install)
  make:
    chdir: "{{ ansible_env.HOME }}/Programs/libinput-gestures"
    target: install
  become: true
  when: libinput_gesture_download.changed
  tags: libinput_gestures

- name: Libinput Gestures (Start and Autorun)
  command: '{{ item }}'
  with_items:
    - libinput-gestures-setup autostart
    - libinput-gestures-setup start
  when: libinput_gesture_download.changed
  tags: libinput_gestures
