# undervolt.yml

---

- name: Install i7z package
  dnf:
    state: present
    name:
      - https://download.copr.fedorainfracloud.org/results/scx/i7z/fedora-rawhide-x86_64/00769928-i7z/i7z-0.27.2-21.20150629gitec09c4f.fc29.x86_64.rpm
  become: true
  when:
    - ansible_distribution == 'Fedora'

- name: Intel-undervolt-tool (Clone)
  git:
    repo: https://github.com/hedgepigdaniel/linux-intel-undervolt-tool/
    dest: '{{ ansible_env.HOME }}/Programs/linux-undervolt-tool'
    version: master
    update: true
  register: intel_undervolt_download

- name: Intel-undervolt-tool (Clone)
  shell: |
    cd {{ ansible_env.HOME }}/Programs/linux-undervolt-tool;
    ./install.sh
  when: intel_undervolt_download.changed
  become: true
  tags: never,undervolt

- name: Set Undervolt daemon timer
  blockinfile:
    path: /etc/systemd/system/undervolt.timer
    create: true
    block: |
      [Unit]
      Description=Runs Undervolt every 20s
      [Timer]
      OnBootSec=20
      OnUnitActiveSec=20
      Unit=undervolt.service
      [Install]
      WantedBy=multi-user.target
  become: true

- name: Undervolt timer enable
  systemd:
    name: undervolt.timer
    state: started
    enabled: true
    daemon_reload: true
  become: true
