---
version: 2
# command define
commands:
    - title: Reload
      command: :reload-config

# linter,formatter setting
tools:

    sh-shellcheck: &sh-shellcheck
        lint-command: shellcheck -Cnever -f gcc -a -Sstyle -x
        lint-ignore-exit-code: true
        lint-formats:
            - '%f:%l:%c: %trror: %m'
            - '%f:%l:%c: %tarning: %m'
            - '%f:%l:%c: %tote: %m'

    sh-shfmt: &sh-shfmt
        format-command: 'shfmt -ci -s -bn'
        format-stdin: true

    man-hover: &man-hover
        hover-command: man ${INPUT}
        hover-stdin: false

    python-autopep8: &python-autopep8
        format-command: 'autopep8 -'
        format-stdin: true

    python-black: &python-black
        format-command: 'black --quiet -'
        format-stdin: true

    python-flake8: &python-flake8
        lint-command: 'flake8 --stdin-display-name ${INPUT} -'
        lint-stdin: true
        lint-formats:
            - '%f:%l:%c: %m'

    python-isort: &python-isort
        format-command: 'isort --quiet -'
        format-stdin: true

    python-mypy: &python-mypy
        lint-command: 'mypy --show-column-numbers'
        lint-formats:
            - '%f:%l:%c: %trror: %m'
            - '%f:%l:%c: %tarning: %m'
            - '%f:%l:%c: %tote: %m'

    python-pylint: &python-pylint
        lint-command: 'pylint --output-format text --score no --msg-template {path}:{line}:{column}:{C}:{msg} ${INPUT}'
        lint-stdin: false
        lint-formats:
            - '%f:%l:%c:%t:%m'
        lint-offset-columns: 1
        lint-category-map:
            I: H
            R: I
            C: I
            W: W
            E: E
            F: E

    python-yapf: &python-yapf
        format-command: 'yapf --quiet'
        format-stdin: true

    yamllint-lint: &yamllint-lint
        lint-command: yamllint -c /home/luca-linux/yamllint.yml --format parsable ${INPUT}
        lint-ignore-exit-code: true
        lint-stdin: false
        lint-formats:
            - '%f:%l:%c: [%trror] %m'
            - '%f:%l:%c: [%tarning] %m'
        env:
            - PYTHONIOENCODING=UTF-8

    json-jq: &json-jq
        lint-command: 'jq .'

# languages setting
languages:
    json:
        - <<: *json-jq

    sh:
        - <<: *sh-shellcheck
        - <<: *sh-shfmt
        - <<: *man-hover

    yaml:
        - <<: *yamllint-lint

    python:
        - <<: *python-black
        - <<: *python-flake8
        - <<: *python-isort
        - <<: *python-mypy
        - <<: *python-autopep8
        - <<: *python-yapf
