---
# tasks file for dotfiles

- name: Check if Baseline folder is present
  file:
    path: '{{ item }}'
    state: directory
  with_items:
    - '{{ ansible_env.HOME }}/.config/alacritty'
    - '{{ ansible_env.HOME }}/.config/autostart'
    - '{{ ansible_env.HOME }}/.config/devilspie2'
    - '{{ ansible_env.HOME }}/.config/mpv'
    - '{{ ansible_env.HOME }}/.config/systemd'
    - '{{ ansible_env.HOME }}/.config/systemd/user'
    - '{{ ansible_env.HOME }}/.local/go'
    - '{{ ansible_env.HOME }}/.local/rust'
    - '{{ ansible_env.HOME }}/.local/share'
    - '{{ ansible_env.HOME }}/.ssh/'
    - '{{ ansible_env.HOME }}/.vim'
    - '{{ ansible_env.HOME }}/.vim/autoload'
    - '{{ ansible_env.HOME }}/.vim/swap'
    - '{{ ansible_env.HOME }}/.vim/syntax'
    - '{{ ansible_env.HOME }}/.vim/undo'
    - '{{ ansible_env.HOME }}/.vim/view'
  register: firstrun

- name: Install vim-plug
  get_url:
    url: '{{ item.src }}'
    dest: '{{ item.dest }}'
    mode: 0755
  with_items:
    - {src: "https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim", dest: '{{ ansible_env.HOME }}/.vim/autoload'}

- name: Prepare to link dotfiles
  file:
    path: '{{ item }}'
    state: absent
  with_items:
    - '{{ ansible_env.HOME }}/.Xdefaults'
    - '{{ ansible_env.HOME }}/.aliases'
    - '{{ ansible_env.HOME }}/.ansible.cfg'
    - '{{ ansible_env.HOME }}/.bashrc'
    - '{{ ansible_env.HOME }}/.clang-format'
    - '{{ ansible_env.HOME }}/.config/alacritty'
    - '{{ ansible_env.HOME }}/.config/autostart'
    - '{{ ansible_env.HOME }}/.config/devilspie2'
    - '{{ ansible_env.HOME }}/.config/mpv'
    - '{{ ansible_env.HOME }}/.ctags'
    - '{{ ansible_env.HOME }}/.gitconfig'
    - '{{ ansible_env.HOME }}/.gitignore'
    - '{{ ansible_env.HOME }}/.histfile'
    - '{{ ansible_env.HOME }}/.local/share/applications'
    - '{{ ansible_env.HOME }}/.rclone.conf'
    - '{{ ansible_env.HOME }}/.skippyrc'
    - '{{ ansible_env.HOME }}/.ssh/config'
    - '{{ ansible_env.HOME }}/.tmux.conf'
    - '{{ ansible_env.HOME }}/.toprc'
    - '{{ ansible_env.HOME }}/.vimrc'
    - '{{ ansible_env.HOME }}/.vimrc-minimal'
    - '{{ ansible_env.HOME }}/.xbindkeysrc'
    - '{{ ansible_env.HOME }}/.xscreensaver'
    - '{{ ansible_env.HOME }}/.zshrc'

  when: firstrun.changed

- name: link dotfiles
  file:
    src: '{{ item.src }}'
    dest: '{{ item.dest }}'
    state: link
  with_items:
    - {src: '{{ ansible_env.HOME }}/Syncthing/Conf/.histfile', dest: '{{ ansible_env.HOME }}/.histfile'}
    - {src: '{{ ansible_env.HOME }}/dotfiles/.Xdefaults', dest: '{{ ansible_env.HOME }}/.Xdefaults'}
    - {src: '{{ ansible_env.HOME }}/dotfiles/.aliases', dest: '{{ ansible_env.HOME }}/.aliases'}
    - {src: '{{ ansible_env.HOME }}/dotfiles/.ansible.cfg', dest: '{{ ansible_env.HOME }}/.ansible.cfg'}
    - {src: '{{ ansible_env.HOME }}/dotfiles/.bashrc', dest: '{{ ansible_env.HOME }}/.bashrc'}
    - {src: '{{ ansible_env.HOME }}/dotfiles/.clang-format', dest: '{{ ansible_env.HOME }}/.clang-format'}
    - {src: '{{ ansible_env.HOME }}/dotfiles/.ctags', dest: '{{ ansible_env.HOME }}/.ctags'}
    - {src: '{{ ansible_env.HOME }}/dotfiles/.gitconfig', dest: '{{ ansible_env.HOME }}/.gitconfig'}
    - {src: '{{ ansible_env.HOME }}/dotfiles/.gitignore', dest: '{{ ansible_env.HOME }}/.gitignore'}
    - {src: '{{ ansible_env.HOME }}/dotfiles/.rclone.conf', dest: '{{ ansible_env.HOME }}/.rclone.conf'}
    - {src: '{{ ansible_env.HOME }}/dotfiles/.skippyrc', dest: '{{ ansible_env.HOME }}/.skippyrc'}
    - {src: '{{ ansible_env.HOME }}/dotfiles/.tmux.conf', dest: '{{ ansible_env.HOME }}/.tmux.conf'}
    - {src: '{{ ansible_env.HOME }}/dotfiles/.toprc', dest: '{{ ansible_env.HOME }}/.toprc'}
    - {src: '{{ ansible_env.HOME }}/dotfiles/.vimrc', dest: '{{ ansible_env.HOME }}/.vimrc'}
    - {src: '{{ ansible_env.HOME }}/dotfiles/.vimrc-minimal' , dest: '{{ ansible_env.HOME }}/.vimrc-minimal'}
    - {src: '{{ ansible_env.HOME }}/dotfiles/.xbindkeysrc', dest: '{{ ansible_env.HOME }}/.xbindkeysrc'}
    - {src: '{{ ansible_env.HOME }}/dotfiles/.xscreensaver', dest: '{{ ansible_env.HOME }}/.xscreensaver'}
    - {src: '{{ ansible_env.HOME }}/dotfiles/.zshrc', dest: '{{ ansible_env.HOME }}/.zshrc'}
    - {src: '{{ ansible_env.HOME }}/dotfiles/alacritty', dest: '{{ ansible_env.HOME }}/.config/alacritty'}
    - {src: '{{ ansible_env.HOME }}/dotfiles/applications', dest: '{{ ansible_env.HOME }}/.local/share/applications'}
    - {src: '{{ ansible_env.HOME }}/dotfiles/autostart', dest: '{{ ansible_env.HOME }}/.config/autostart'}
    - {src: '{{ ansible_env.HOME }}/dotfiles/devilspie2', dest: '{{ ansible_env.HOME }}/.config/devilspie2'}
    - {src: '{{ ansible_env.HOME }}/dotfiles/mpv', dest: '{{ ansible_env.HOME }}/.config/mpv'}
    - {src: '{{ ansible_env.HOME }}/dotfiles/ssh-config', dest: '{{ ansible_env.HOME }}/.ssh/config'}
    - {src: '{{ ansible_env.HOME }}/dotfiles/systemd/syncthing.service', dest: '{{ ansible_env.HOME }}/.config/systemd/user/syncthing.service'}
  when: firstrun.changed

- name: Enable systemd user services
  systemd:
    name: "{{ item }}"
    state: started
    enabled: yes
    scope: user
  with_items:
    - syncthing.service
