# Creation Date: 2019-06-17
#
# Author: Luca Di Maio
---
# file: main.yml

- hosts: all
  gather_facts: True
  roles:
    - distro_setup
    - packages
    - dotfiles

  vars_files:
    - "vars/distribution/{{ ansible_distribution }}.yml"
