# Creation Date: 2019-06-17
#
# Author: Luca Di Maio
---
# file: main.yml

- hosts: all
  gather_facts: True
  pre_tasks:

    - name: Detect is we're inside a toolbox
      command: systemctl status
      register: inside_toolbox
      failed_when: no
      changed_when: no

    - name: Set fact toolbox
      set_fact:
        is_toolbox: "{% if inside_toolbox.rc == 0 %}false{% else %}true{% endif %}"

  roles:
    - distro_setup
    - packages
    - dotfiles

  vars_files:
    - "vars/distribution/{{ ansible_distribution }}.yml"
