---
- name: Check if {{ item }} is a link
  stat:
    path: "{{ item }}"
  register: is_symlink

- name: Delete {{ item }} if not a symlink
  file:
    path: "{{ item }}"
    state: absent
  when: is_symlink.stat.exists and not is_symlink.stat.islnk
