---
# tasks file for dotfiles

- name: Check if Vim Baseline folder is present
  file:
    path: "{{ item }}"
    state: directory
    mode: 0700
  with_items:
    - "{{ ansible_env.HOME }}/.vim"
    - "{{ ansible_env.HOME }}/.vim/autoload"
    - "{{ ansible_env.HOME }}/.vim/swap"
    - "{{ ansible_env.HOME }}/.vim/syntax"
    - "{{ ansible_env.HOME }}/.vim/undo"
    - "{{ ansible_env.HOME }}/.vim/view"
  register: firstrun

- name: Prepare to link dotfiles
  file:
    path: "{{ item }}"
    state: absent
  with_items:
    - "{{ ansible_env.HOME }}/.Xdefaults"
    - "{{ ansible_env.HOME }}/.aliases"
    - "{{ ansible_env.HOME }}/.bashrc"
    - "{{ ansible_env.HOME }}/.gitconfig"
    - "{{ ansible_env.HOME }}/.histfile"
    - "{{ ansible_env.HOME }}/.tmux.conf"
    - "{{ ansible_env.HOME }}/.toprc"
    - "{{ ansible_env.HOME }}/.vimrc"
    - "{{ ansible_env.HOME }}/.zshrc"
  when: firstrun.changed

- name: Install vim-plug
  get_url:
    url: "{{ item.src }}"
    dest: "{{ item.dest }}"
    mode: 0755
  with_items:
    - {
      src: "https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim",
      dest: "{{ ansible_env.HOME }}/.vim/autoload",
    }

- name: Link dotfiles
  command: "{{ ansible_env.HOME }}/dotfiles/bin/.local/bin/dotfiles"
  when: firstrun.changed
