# Creation Date: 2019-06-17
#
# Author: Luca Di Maio
---
# file: main.yml

- hosts: all
  gather_facts: True

  vars_files:
    - "vars/distribution/{{ ansible_distribution }}.yml"

  pre_tasks:

    - name: Detect is we're inside a container
      command: systemctl status
      register: inside_container
      failed_when: no
      changed_when: no
      tags: always

    - name: Set fact container
      set_fact:
        is_container: "{% if inside_container.rc == 0 %}false{% else %}true{% endif %}"
      tags: always

  roles:
    - {role: distro_setup, when: not is_container, become: yes}
      #    - {role: packages, when: (container_enabled|bool == false) or is_container}
      #    - dotfiles
