# Creation Date: 2019-06-17
#
# Author: Luca Di Maio
---
# file: main.yml

- hosts: all
  gather_facts: True

  vars_files:
    - "vars/distribution/{{ ansible_distribution }}.yml"

  pre_tasks:

    - name: Detect is we're inside a toolbox
      command: systemctl status
      register: inside_toolbox
      failed_when: no
      changed_when: no
      tags: always

    - name: Set fact toolbox
      set_fact:
        is_toolbox: "{% if inside_toolbox.rc == 0 %}false{% else %}true{% endif %}"
      tags: always

  roles:
    - {role: distro_setup, when: not is_toolbox}
    - packages
    - dotfiles
