---
# tweaks
#

- name: Mask services /1
  systemd:
    name: "{{ item }}"
    state: stopped
    enabled: false
    masked: true
    daemon_reload: true
    scope: user
  with_items: "{{ systemd_user_mask_services }}"
  become: false

- name: Mask services /2
  systemd:
    name: "{{ item }}"
    state: stopped
    enabled: false
    masked: true
    daemon_reload: true
  with_items: "{{ systemd_root_mask_services }}"
  become: true

- name: Update fstab file with tmpfs /tmp
  lineinfile:
    path: /etc/fstab
    regexp: tmpfs /tmp tmpfs
    line: tmpfs /tmp tmpfs defaults,lazytime,noatime,nodiratime 0 0
    state: present
    backup: true
  become: true

- name: Discard Trim Enable
  systemd:
    name: fstrim.timer
    state: started
    enabled: true
    daemon_reload: true
  become: true

- name: Load IO Schedulers at boot
  blockinfile:
    path: /etc/modules-load.d/iosched.conf
    create: true
    block: |
      bfq
      mq-deadline
      kyber-iosched
  become: true

- name: Responsiveness process performance-tweaks
  capabilities:
    path: "{{ item }}"
    capability: cap_sys_nice=+ep
    state: present
  with_items: "{{ process_prioritize }}"
  become: true

- name: Update the profiles file with personal variables
  lineinfile:
    path: /etc/profile
    regexp: '{{ item }}'
    line: '{{ item }}'
    state: present
    backup: true
  with_items: "{{ global_vars }}"
  become: true
