---
# vars file for my_apps
#

use_flatpaks: yes

flatpak_packages:
  - us.zoom.Zoom
  - com.github.tchx84.Flatseal
  - org.gnome.Calculator
  - org.gnome.Calendar
  - org.gnome.Connections
  - org.gnome.Contacts
  - org.gnome.Epiphany
  - org.gnome.Evince
  - org.gnome.FileRoller
  - org.gnome.Logs
  - org.gnome.Maps
  - org.gnome.NetworkDisplays
  - org.gnome.Rhythmbox3
  - org.gnome.SoundRecorder
  - org.gnome.Totem
  - org.gnome.Weather
  - org.gnome.baobab
  - org.gnome.clocks
  - org.gnome.eog
  - org.gnome.gedit
  - org.kde.krita
  - org.keepassxc.KeePassXC
  - org.libreoffice.LibreOffice # org.onlyoffice.desktopeditors
  - org.chromium.Chromium
  - org.mozilla.firefox
  - org.mozilla.Thunderbird
  - org.remmina.Remmina
  - org.libretro.RetroArch
  - com.github.polymeilex.neothesia
  - com.github.jeromerobert.pdfarranger
  - com.github.johnfactotum.Foliate
  - com.github.maoschanz.drawing
  - com.jgraph.drawio.desktop
  - de.haeckerfelix.Fragments
  - fyi.zoey.Boop-GTK
  - nl.hjdskes.gcolor3

flatpak_duplicate_packages:
  - zoom
  - flatseal
  - baobab
  - chromium
  - drawing
  - drawio
  - eog
  - epiphany
  - evince
  - file-roller
  - firefox
  - foliate
  - fragments
  - gcolor3
  - gedit
  - gnome-calculator
  - gnome-calendar
  - gnome-clocks
  - gnome-connections
  - gnome-contacts
  - gnome-logs
  - gnome-maps
  - gnome-network-displays
  - gnome-sound-recorder
  - gnome-weather
  - keepassxc
  - krita
  - libreoffice
  - neothesia
  - pdfarranger
  - remmina
  - retroarch
  - rhythmbox
  - thunderbird
  - totem

flatpak_overrides:
  - {key: "org.mozilla.firefox", value: "MOZ_ACCELLERATED=1"}
  - {key: "org.mozilla.firefox", value: "MOZ_USE_XINPUT2=1"}
  - {key: "org.mozilla.firefox", value: "MOZ_WEBRENDER=1"}
  - {key: "org.mozilla.firefox", value: "MOZ_X11_EGL=1"}

python_packages:
  - python3
  - python3-pip

python_modules:
  - "python-lsp-server[all]"
  - pyls-flake8
  - pyls-isort
  - flake8-awesome
  - flake8-docstrings
  - flake8-eradicate
  - setuptools
  - ansible==2.9
  - ansible-later
  - ansible-lint
  - demjson
  - indicator-syncthing
  - neovim
  - psutil
  - six
  - yamllint
  # - "https://github.com/ssokolow/quicktile/archive/master.zip"

golang_packages:
  - golang

golang_modules:
  - golang.org/x/lint/golint
  - golang.org/x/tools/cmd/goimports
  - golang.org/x/tools/cmd/gorename
  - golang.org/x/tools/cmd/guru
  - mvdan.cc/sh/cmd/shfmt
