---
# vars file for debloat
#

debloat_pkg:
    - PackageKit-command-not-found
    - PackageKit-gstreamer-plugin
    - PackageKit-gtk3-module
    - aajohan-comfortaa-fonts
    - cheese
    - desktop-backgrounds-gnome
    - fedora-bookmarks
    - fedora-chromium-config
    - fedora-workstation-backgrounds
    - gamemode
    - gnome-abrt
    - gnome-backgrounds
    - gnome-boxes
    - gnome-calendar
    - gnome-characters
    - gnome-classic-session
    - gnome-clocks
    - gnome-contacts
    - gnome-documents
    - gnome-font-viewer
    - gnome-getting-started-docs
    - gnome-initial-setup
    - gnome-logs
    - gnome-maps
    - gnome-music
    - gnome-online-miners
    - gnome-photos
    - gnome-shell-extension-apps-menu
    - gnome-shell-extension-background-logo
    - gnome-shell-extension-horizontal-workspaces
    - gnome-shell-extension-launch-new-instance
    - gnome-shell-extension-places-menu
    - gnome-shell-extension-window-list
    - gnome-software
    - gnome-user-docs
    - gnome-user-share
    - gnome-video-effects
    - gnome-weather
    - google-noto-emoji-color-fonts
    - google-noto-sans-cjk-ttc-fonts
    - google-noto-sans-gurmukhi-fonts
    - google-noto-sans-sinhala-vf-fonts
    - httpd
    - hyperv-daemons
    - ibus-hangul
    - ibus-kkc
    - ibus-libpinyin
    - ibus-libzhuyin
    - ibus-m17n
    - ibus-qt
    - ibus-typing-booster
    - jomolhari-fonts
    - julietaula-montserrat-fonts
    - khmeros-base-fonts
    - lohit-assamese-fonts
    - lohit-bengali-fonts
    - lohit-devanagari-fonts
    - lohit-gujarati-fonts
    - lohit-kannada-fonts
    - lohit-odia-fonts
    - lohit-tamil-fonts
    - lohit-telugu-fonts
    - lrzsz
    - mpage
    - open-vm-tools-desktop
    - orca
    - paktype-naskh-basic-fonts
    - paps
    - paratype-pt-sans-fonts
    - pinentry-gnome3
    - podman
    - qemu-guest-agent
    - rdist
    - rhythmbox
    - rpmfusion-free-appstream-data
    - rpmfusion-nonfree-appstream-data
    - shotwell
    - sil-abyssinica-fonts
    - sil-mingzat-fonts
    - sil-nuosu-fonts
    - sil-padauk-fonts
    - simple-scan
    - smc-meera-fonts
    - spice-vdagent
    - stix-fonts
    - sushi
    - thai-scalable-waree-fonts
    - totem
    - unoconv
    - virtualbox-guest-additions
    - yelp

debloat_pkg_extreme:
    - virt-manager
    - libvirt
    - libvirt-bash-completion
    - libvirt-client
    - libvirt-daemon
    - libvirt-daemon-config-network
    - libvirt-daemon-config-nwfilter
    - libvirt-daemon-driver-interface
    - libvirt-daemon-driver-libxl
    - libvirt-daemon-driver-lxc
    - libvirt-daemon-driver-network
    - libvirt-daemon-driver-nodedev
    - libvirt-daemon-driver-nwfilter
    - libvirt-daemon-driver-qemu
    - libvirt-daemon-driver-secret
    - libvirt-daemon-driver-storage
    - libvirt-daemon-driver-storage-core
    - libvirt-daemon-driver-storage-disk
    - libvirt-daemon-driver-storage-gluster
    - libvirt-daemon-driver-storage-iscsi
    - libvirt-daemon-driver-storage-iscsi-direct
    - libvirt-daemon-driver-storage-logical
    - libvirt-daemon-driver-storage-mpath
    - libvirt-daemon-driver-storage-rbd
    - libvirt-daemon-driver-storage-scsi
    - libvirt-daemon-driver-storage-sheepdog
    - libvirt-daemon-driver-storage-zfs
    - libvirt-daemon-driver-vbox
    - libvirt-daemon-kvm
    - libvirt-glib
    - libvirt-libs

systemd_user_mask_services:
    - tracker-miner-fs
    - evolution-addressbook-factory
    - evolution-source-registry
    - evolution-calendar-factory

systemd_root_mask_services:
    - switcheroo-control
